"use strict";
// Game configuration from the admin console (docs/admin-console.md): the server's overrides of the built-in balance
// tables. js/gcfgdata.js (generated by the server, loaded right before this file) sets window.GCFG_BOOT =
// {v, sections: {name: document}}; sections without an override are absent and the game keeps its built-ins.
//
//   GCFG.v                               version of the active configuration (0 = none)
//   GCFG.get("drops", "normal", 0.08)    a value (path "a.b.c" or ["a", "b"]) or the fallback
//   GCFG.doc("drops")                    the whole document or null
//   GCFG.on("drops", (doc, old) => …)    apply a section: called at once (if it has a document) and on every change
//                                        of it afterwards (doc = null when it went back to the defaults)
//   GCFG.keep("MON", () => MON)          deep copy of a built-in table taken the first time (to restore defaults)
//   GCFG.applyPatch(state, ops)          replay admin save edits (server/admin_console.py apply_patch) — js/net.js
//
// Hook files js/gcfg/<section>.js go after the scripts defining the tables they change (index.html, before main.js).
// While playing, the version is re-checked every 60 s (and when the tab comes back): /api/config with its ETag.
(function () {
  const boot = window.GCFG_BOOT && typeof window.GCFG_BOOT === "object" ? window.GCFG_BOOT : { v: 0, sections: {} };
  const hooks = {};
  const kept = {};
  const G = {
    v: +boot.v || 0,
    sections: boot.sections && typeof boot.sections === "object" ? boot.sections : {},
    served: !!window.GCFG_BOOT,
    changedAt: 0,
  };
  const split = (p) => (Array.isArray(p) ? p : p == null || p === "" ? [] : String(p).split("."));
  G.doc = (name) => (Object.prototype.hasOwnProperty.call(G.sections, name) ? G.sections[name] : null);
  G.get = (name, path, fb) => {
    let v = G.doc(name);
    if (v == null) return fb;
    for (const k of split(path)) {
      if (v == null || typeof v !== "object" || !(k in v)) return fb;
      v = v[k];
    }
    return v === undefined || v === null ? fb : v;
  };
  /** number with a sane fallback (NaN / non-number documents never break the game) */
  G.num = (name, path, fb) => {
    const v = G.get(name, path, fb);
    return typeof v === "number" && isFinite(v) ? v : fb;
  };
  const run = (name, fn, doc, old) => {
    try {
      fn(doc, old);
    } catch (e) {
      console.warn("GCFG hook " + name + ":", e);
    }
  };
  G.on = (name, fn) => {
    (hooks[name] = hooks[name] || []).push(fn);
    const d = G.doc(name);
    d != null && run(name, fn, d, null);
  };
  G.keep = (key, get) => {
    if (!(key in kept)) {
      try {
        kept[key] = JSON.parse(JSON.stringify(get()));
      } catch {
        kept[key] = undefined;
      }
    }
    return kept[key] === undefined ? undefined : JSON.parse(JSON.stringify(kept[key]));
  };
  /** new configuration {v, sections}: swap it in and run the hooks of every section whose document changed */
  G.set = (cfg) => {
    if (!cfg || typeof cfg !== "object" || !(+cfg.v >= 0)) return false;
    const old = G.sections;
    const nu = cfg.sections && typeof cfg.sections === "object" ? cfg.sections : {};
    G.v = +cfg.v;
    G.sections = nu;
    G.changedAt = Date.now();
    const names = new Set([...Object.keys(old), ...Object.keys(nu)]);
    for (const n of names) {
      if (JSON.stringify(old[n]) === JSON.stringify(nu[n])) continue;
      for (const fn of hooks[n] || []) run(n, fn, nu[n] == null ? null : nu[n], old[n] == null ? null : old[n]);
    }
    return true;
  };
  G.applyPatch = (st, ops) => {
    if (!st || !Array.isArray(ops)) return;
    for (const o of ops) {
      if (!Array.isArray(o) || !Array.isArray(o[1]) || !o[1].length) continue;
      const [op, path] = o;
      let cur = st,
        ok = true;
      for (const k of path.slice(0, -1)) {
        if (cur && typeof cur === "object" && !Array.isArray(cur) && typeof k === "string") {
          if (!cur[k] || typeof cur[k] !== "object") {
            if (op === "del") {
              ok = false;
              break;
            }
            cur[k] = {};
          }
          cur = cur[k];
        } else if (Array.isArray(cur) && typeof k === "number" && k >= 0 && k < cur.length && cur[k] && typeof cur[k] === "object") cur = cur[k];
        else {
          ok = false;
          break;
        }
      }
      if (!ok) continue;
      const last = path[path.length - 1];
      const isMap = cur && typeof cur === "object" && !Array.isArray(cur) && typeof last === "string";
      const isArr = Array.isArray(cur) && typeof last === "number" && last >= 0 && last < cur.length;
      if (!isMap && !isArr) continue;
      if (op === "set") cur[last] = o[2] && typeof o[2] === "object" ? JSON.parse(JSON.stringify(o[2])) : o[2];
      else if (op === "inc") cur[last] = (typeof cur[last] === "number" ? cur[last] : 0) + (+o[2] || 0);
      else if (op === "del") isArr ? cur.splice(last, 1) : delete cur[last];
    }
  };
  // live updates: poll /api/config (ETag) while the game runs on a server
  let etag = '"cfg-' + G.v + '"',
    busy = false,
    last = 0;
  G.check = async () => {
    if (busy || !G.served || !/^https?:$/.test(location.protocol)) return false;
    busy = true;
    last = Date.now();
    try {
      const r = await fetch("/api/config", { headers: { "If-None-Match": etag }, cache: "no-cache" });
      if (r.status !== 200) return false;
      const cfg = await r.json();
      etag = r.headers.get("ETag") || etag;
      if (+cfg.v === G.v) return false;
      G.set(cfg);
      typeof window.gcfgChanged === "function" && window.gcfgChanged(G.v);
      return true;
    } catch {
      return false;
    } finally {
      busy = false;
    }
  };
  if (G.served) {
    setInterval(G.check, 60e3);
    document.addEventListener("visibilitychange", () => document.hidden || Date.now() - last < 15e3 || G.check());
  }
  window.GCFG = G;
})();
