"use strict";
// Thần Hành Phù — reusable teleport talisman (like JX1): pick a destination and travel there.
// Destinations = the JX1 item script \script\mineitem\ib\shenxingfu.lua (thanhanh_dest.js, generated by
// tools/jxmap/thdest.py): Thành thị / Thôn trang / Môn phái / Luyện công (by level) / Tống Kim, plus the
// game's own farming zones (mode.js gotoZone).
//   - safe maps (City / Country / Capital / Battlefield, JX1 fight mode 0) -> town mode: the map becomes
//     "the town" (W.town: shop, stash, Kỳ Trân Các, regen) and Thổ Địa Phù's return point (S.thTown).
//   - a map that is a farming zone (or one of its alt maps) -> that zone, level gating as before.
//   - any other map -> field mode: registered as a temporary alt map of the zone matching its level, so the
//     zone's monsters / levels / boss apply (gated like that zone); camps sit around the JX1 landing point.
// Landing points are JX1's (NewWorld coords converted to full-map px).
// Self-contained: hooks into existing globals so other files stay untouched.
const TH_KEY = "thp", // misc material key (S.mats.misc.thp)
  TH_NAME = "Thần Hành Phù",
  TH_CD = 30, // seconds
  TH_GOLD = 2e3, // price in Cửa hàng / Kỳ Trân Các
  TH_IC = "img/ep/ldp.png?th", // Thổ Địa Phù's token, hue-shifted by CSS (see TH_CSS)
  TH_TOWN0 = typeof W == "object" && W.town ? Object.assign({}, W.town) : { id: 37, n: "Biện Kinh", bg: "" },
  thHave = () => (typeof matHave == "function" && S && S.mats ? matHave("misc", TH_KEY) : 0),
  thCdLeft = () => Math.max(0, ((R.thAt || 0) - Date.now()) / 1e3),
  thCur = () => zoneIdx(Math.min(S.stage, STAGES)),
  thLv = (z) => Math.max(1, z.lo - 3), // zoneOpen(): lo <= effLv() + 3
  thDests = () => (window.TH_DEST && Array.isArray(TH_DEST.dest) ? TH_DEST.dest : []),
  thDest = (id) => thDests().find((d) => String(d.id) === String(id)),
  thFold = (s) =>
    String(s || "")
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/đ/g, "d")
      .replace(/Đ/g, "D")
      .toLowerCase();
let thQ = ""; // picker search text

// Optional full-map preview: only for maps already cached on this device (js/jxmap.js jxmThumb: object URL).
function thThumb(id) {
  try {
    return typeof jxmThumb == "function" ? jxmThumb(id) : "";
  } catch {
    return "";
  }
}
function thMapName(id, n) {
  try {
    const m = window.JMAP && window.JMAP[id];
    return n || (m && m.name) || "";
  } catch {
    return n;
  }
}
// Map data available? Server / static export index (map/index.js), or the old baked town / zone images.
function thAvail(d) {
  if (thZoneKey(d.id)) return !0;
  if (String(d.id) === String(TH_TOWN0.id)) return !0;
  return typeof JXM == "object" && JXM.idx instanceof Set && JXM.idx.has(String(d.id));
}
// Farming zone / alt map for a map id -> [zone, alt] (alt 0 = the zone map itself), ignoring visit alts.
function thZoneKey(id) {
  for (let z = 0; z < ZONES.length; z++) {
    if (String(ZONES[z].id) === String(id)) return [z, 0];
    const a = (ZALT[z] || []).findIndex((m) => !m.thv && String(m.id) === String(id));
    if (a >= 0) return [z, a + 1];
  }
  return null;
}
// Level of a destination: JX1 "Luyện công · Cấp N" list (N..N+9), else MapList npc level, else 10.
const thDLv = (d) => (d.lv ? d.lv + 5 : d.mlv ? Math.round((d.mlv[0] + d.mlv[1]) / 2) : 10);
// Zone whose level range fits lv (its monsters / gating are used on a field visit).
function thZoneFor(lv) {
  let b = 0;
  ZONES.forEach((z, i) => {
    z.lo <= lv && (b = i);
  });
  return b;
}
// Register map d as a temporary alt map of zone z (one visit map at a time). -> alt index (1-based)
function thVisitAlt(z, d) {
  for (const k in ZALT) {
    const l = ZALT[k],
      i = l.findIndex((m) => m.thv);
    if (i >= 0 && !(+k === z && String(l[i].id) === String(d.id))) {
      l.splice(i, 1);
      S.zalt && S.zalt[k] > i && (S.zalt[k] = 0);
    }
  }
  const Z = ZONES[z],
    l = ZALT[z] || (ZALT[z] = []),
    i = l.findIndex((m) => m.thv);
  if (i >= 0) return i + 1;
  l.push({ lo: Z.lo, hi: Z.hi, sw: Z.sw, boss: Z.boss, alt: !0, id: d.id, n: d.n, bg: "", m: Z.m, thv: 1 });
  return l.length;
}
// Make the safe map d "the town" (shop / stash / Thổ Địa Phù target), like JX1's return point.
function thSetTown(d) {
  if (!d || typeof W != "object" || !W.town) return;
  const own = String(d.id) === String(TH_TOWN0.id);
  Object.assign(W.town, { id: d.id, n: d.n, bg: own ? TH_TOWN0.bg : "" });
  S && (String(d.id) === String(TH_TOWN0.id) ? delete S.thTown : (S.thTown = d.id));
  const tn = $("#townName");
  tn && R.town && (tn.textContent = d.n);
}
// What a destination does: {kind: "town" | "zone" | "visit", z, a, lock, need, sub}
function thPlan(d) {
  if (d.safe) return { kind: "town" };
  if (typeof miguIs == "function" && miguIs(d)) {
    // Nguyệt Ca Mật Cốc (js/migu.js): own entry level, paid pass, monsters of its own level band
    const c = miguCfg();
    return { kind: "visit", z: thZoneFor(c.mlv[0]), lock: effLv() < c.minLv, need: c.minLv, migu: 1 };
  }
  const zk = thZoneKey(d.id);
  if (zk) {
    const [z, a] = zk;
    return { kind: "zone", z, a, lock: !zoneOpen(z), need: thLv(ZONES[z]) };
  }
  const z = thZoneFor(thDLv(d));
  return { kind: "visit", z, lock: !zoneOpen(z), need: thLv(ZONES[z]) };
}

// Why the talisman can't be used right now ("" = ok).
function thBlocked() {
  if (!S || !S.fac) return "Chưa vào giang hồ";
  if (R.dg) return R.dg.kind === "boat" ? "Đang đi thuyền" : "Đang trong phó bản / boss tuần";
  if (R.tower) return "Đang ở Tháp thử thách";
  if (R.sat) return "Đang truy sát Sát Thủ";
  if (R.deadT > 0) return "Đang trọng thương";
  return "";
}
function thUse() {
  if (!S || !S.fac) return;
  if (thHave() < 1) {
    toast(`Chưa có ${TH_NAME} (mua ở Cửa hàng ${W.town.n} hoặc Kỳ Trân Các)`);
    return;
  }
  const b = thBlocked();
  if (b) {
    toast(b);
    return;
  }
  if (thCdLeft() > 0) {
    toast(`${TH_NAME} hồi sau ${Math.ceil(thCdLeft())} giây`);
    return;
  }
  thModal();
}
// One row. o: {k, n, sub, cur, lock, need, alt, thumb, na (no map data), pts [[label, key]], adm}
function thRow(o) {
  const t = o.thumb ? `<img src="${esc(o.thumb)}" alt="" loading="lazy" onerror="this.style.visibility='hidden'">` : "",
    dis = (o.lock && !o.adm) || o.na,
    attr = o.adm ? `data-a="go:${o.k}"` : `data-th="${o.k}"`,
    em = o.cur ? "Đang ở đây" : o.na ? "Chưa có bản đồ" : o.lock ? (o.adm ? "Mở & đi" : `Cần cấp ${o.need}`) : "Đi",
    row = `<button class="shoprow thrw${o.alt ? " alt" : ""}${o.cur ? " own" : ""}${o.lock || o.na ? " bad" : ""}${t ? "" : " nt"}" ${attr} ${dis ? "disabled" : ""} data-q="${esc(thFold(o.n + " " + (o.q || "")))}">${t}<span><b>${esc(o.n)}</b><small>${o.sub}</small></span><em>${em}</em></button>`;
  if (!o.pts || o.pts.length < 2 || o.na) return row;
  const ch = o.pts
    .map(([l, k]) => `<button class="btn sm" ${o.adm ? `data-a="go:${k}"` : `data-th="${k}"`}>${esc(l)}</button>`)
    .join("");
  return `<div class="thgrp" data-q="${esc(thFold(o.n + " " + (o.q || "")))}">${row}<div class="thpts">${ch}</div></div>`;
}
// The whole destination list (picker and admin world tab). adm: rows use data-a="go:<key>", no gating.
function thListHTML(adm) {
  const out = [],
    cz = thCur(),
    ca = (S.zalt || {})[cz] || 0,
    curZone = !R.town && zoneOf(Math.min(S.stage, STAGES)),
    G = window.TH_DEST && Array.isArray(TH_DEST.groups) && TH_DEST.groups.some((g) => g[0] === "train") ? TH_DEST.groups : [["train", "Luyện công"]],
    D = thDests(),
    hd = (n) => out.push(`<div class="thh">${n}</div>`),
    dRow = (d) => {
      const p = thPlan(d),
        na = !thAvail(d),
        cur = p.kind === "town" ? !!R.town && String(W.town.id) === String(d.id) : !!curZone && String(curZone.id) === String(d.id),
        Z = p.z != null ? ZONES[p.z] : null,
        sub = p.migu
          ? miguSub()
          : p.kind === "town"
            ? `${d.t === "Battlefield" ? "Khu an toàn" : "Thành thị · an toàn"} · cửa hàng · kho chung${String(S.thTown || TH_TOWN0.id) === String(d.id) ? " · nơi về của Thổ Địa Phù" : ""}`
            : p.kind === "zone"
              ? `Bãi luyện công · Cấp ${Z.lo}–${Z.hi}`
              : `${d.lv ? `Luyện công cấp ${d.lv}` : "Dã ngoại"} · quái như ${esc(Z.n)} (cấp ${Z.lo}–${Z.hi})`;
      return thRow({
        k: `v:${d.id}`,
        n: d.n,
        sub,
        cur,
        lock: p.lock,
        need: p.need,
        na,
        adm,
        q: d.g,
        thumb: thThumb(d.id),
        pts: d.p && d.p.map((pt, i) => [pt[0], `v:${d.id}:${i}`]),
      });
    };
  // Current town first (Thổ Địa Phù target) when it is not one of the cities.
  const cities = D.filter((d) => d.g === "city");
  if (!cities.some((d) => String(d.id) === String(W.town.id)))
    out.push(
      thRow({
        k: "town",
        n: W.town.n,
        sub: "Hồi phục · cửa hàng · Kỳ Trân Các · kho chung",
        cur: !!R.town,
        adm,
        thumb: thThumb(W.town.id),
      }),
    );
  for (const [g, gn] of G) {
    if (g === "train") {
      // the game's own farming zones first, then JX1's Luyện công list by level
      hd("Bãi luyện công");
      ZONES.forEach((z, i) => {
        const open = zoneOpen(i),
          dots = typeof seriesDots == "function" ? seriesDots(z) + " " : "";
        [z].concat((ZALT[i] || []).filter((m) => !m.thv)).forEach((m, a) =>
          out.push(
            thRow({
              k: `${i}:${a}`,
              n: thMapName(m.id, m.n),
              sub: `${a ? "" : dots}Cấp ${z.lo}–${z.hi}${a ? ` · bản đồ phụ của ${esc(z.n)}` : ""}`,
              alt: a > 0,
              cur: !R.town && cz === i && ca === a,
              lock: !open,
              need: thLv(z),
              adm,
              thumb: thThumb(m.id),
            }),
          ),
        );
      });
      // Mật Cốc (group "migu") sits with its entry level band (Luyện công · cấp 90)
      const tr = D.filter((d) => (d.g === "train" || d.g === "migu") && !thZoneKey(d.id)).sort((a, b) => (a.lv || 0) - (b.lv || 0));
      let lv = -1;
      for (const d of tr) {
        d.lv !== lv && ((lv = d.lv), hd(`${gn} · cấp ${lv}`));
        out.push(dRow(d));
      }
      continue;
    }
    if (g === "migu") continue; // listed with the level-90 training maps above
    const l = D.filter((d) => d.g === g);
    if (!l.length) continue;
    hd(gn);
    for (const d of l) out.push(dRow(d));
  }
  return out.join("");
}
// Search filter over the rendered list (hides rows not matching, then empty headers).
function thFilter(root, q) {
  const f = thFold(q).trim();
  let hdr = null,
    any = !1;
  const fin = () => hdr && (hdr.hidden = !any);
  for (const el of root.children) {
    if (el.classList.contains("thh")) {
      fin();
      hdr = el;
      any = !1;
      continue;
    }
    const ok = !f || (el.dataset.q || "").includes(f) || thFold(el.textContent).includes(f);
    el.hidden = !ok;
    ok && (any = !0);
  }
  fin();
}
function thModal() {
  typeof jxmIndex == "function" && typeof JXM == "object" && JXM.idx === void 0 && jxmIndex(() => $("#mBody .thlist") && thModal());
  modal(
    `<h3><img src="${TH_IC}" alt="" class="thic"> ${TH_NAME} <small>chọn nơi đến · có ${thHave()} · hồi ${TH_CD} giây</small></h3>
    <input id="thQ" class="thq" type="search" placeholder="Tìm bản đồ (vd: tuong duong, dong, cap 50)…" value="${esc(thQ)}" autocomplete="off">
    <div class="shoplist thlist">${thListHTML(!1)}</div>
    <p class="dim small">Dùng mãi không mất. Thành thị / thôn trang / Tống Kim là khu an toàn (cửa hàng, kho, Thổ Địa Phù sẽ đưa về nơi này). Bản đồ dã ngoại dùng quái của bãi luyện công cùng cấp. Đi tới bãi luyện công sẽ tắt tự đổi bãi theo cấp. Không dùng được trong phó bản, khi đi thuyền, ở Tháp thử thách hoặc khi truy sát Sát Thủ.</p>`,
    () => {
      document.querySelectorAll("#mBody [data-th]").forEach((e) => (e.onclick = () => thPick(e.dataset.th)));
      const l = $("#mBody .thlist"),
        q = $("#thQ");
      q && l && ((q.oninput = () => ((thQ = q.value), thFilter(l, q.value))), thQ && thFilter(l, thQ));
      const c = $("#mBody .thrw.own");
      c && c.scrollIntoView && c.scrollIntoView({ block: "center" });
    },
  );
}
// Picker click: Mật Cốc without an active pass asks first (js/migu.js), everything else travels at once.
function thPick(k) {
  const d = k.startsWith("v:") && thDest(k.split(":")[1]);
  if (d && typeof miguIs == "function" && miguIs(d) && !miguActive()) {
    const b = thBlocked();
    if (b) return toast(b);
    if (thHave() < 1) return toast(`Chưa có ${TH_NAME}`);
    if (thCdLeft() > 0) return toast(`${TH_NAME} hồi sau ${Math.ceil(thCdLeft())} giây`);
    const p = thPlan(d);
    if (p.lock) return toast(`Cần cấp ${p.need}`);
    return miguAsk(k);
  }
  thGo(k);
}
// Display name of a picker key.
function thKeyName(k) {
  if (k === "town") return W.town.n;
  if (k.startsWith("v:")) {
    const [, id, p] = k.split(":"),
      d = thDest(id);
    return d ? (p != null && d.p && d.p[+p] && +p > 0 ? `${d.n} (${d.p[+p][0]})` : d.n) : "";
  }
  const [z, a] = k.split(":").map(Number),
    m = a ? (ZALT[z] || [])[a - 1] : ZONES[z];
  return m ? m.n : "";
}
// Travel to a zone / alt map (same as picking a map in the zone list, ui.js / ui20win.js).
function thToZone(z, a, banner) {
  const zone = ZONES[z],
    m = a ? (ZALT[z] || [])[a - 1] : zone;
  if (!zone || !m) return !1;
  const cz = thCur(),
    ca = (S.zalt || {})[z] || 0;
  if (!R.town && cz === z && ca === a) return (toast(`Đang ở ${m.n}`), !1);
  (S.mode === "quest" || S.mode === "dg") &&
    ((S.mode = "farm"), log("⚔ Chọn bãi luyện công: chuyển sang chế độ Luyện công."));
  S.autoMap = !1;
  (S.zalt || (S.zalt = {}))[z] = a;
  if (!R.town && cz === z) ((S.wave = 1), (R.enemies = []), (R.corpses = []), (R.spawnT = 0.3), (R.zoneShown = null));
  else {
    // leaving a town: put the stage in the target zone first so backFromTown loads the target map directly
    R.town && typeof farmStage == "function" && (S.stage = farmStage(z));
    if (!gotoZone(z, TH_NAME)) return !1;
    R.logs && R.logs[0] && R.logs[0].includes(`${TH_NAME}: tới`) && R.logs.shift(); // logged by thGo instead
  }
  R.pickTarget = null;
  R.moveTo = null;
  INPUT.target = null;
  R.banner = { t: 2.2, text: m.n, sub: banner || `${TH_NAME} · Cấp ${zone.lo}–${zone.hi}` };
  return !0;
}
// Town mode on the current W.town (Thổ Địa Phù's entry, bypassing its cooldown only).
function thToTown() {
  if (R.town) R.town = !1; // switching towns: re-enter
  const cd = R.tpCd;
  R.tpCd = 0;
  goTown();
  R.tpCd = cd;
  if (!R.town) return !1;
  R.logs && R.logs[0] && R.logs[0].includes("Thổ Địa Phù") && R.logs.shift();
  return !0;
}
function thGo(k) {
  const b = thBlocked();
  if (b) return toast(b);
  if (thHave() < 1) return toast(`Chưa có ${TH_NAME}`);
  if (thCdLeft() > 0) return toast(`${TH_NAME} hồi sau ${Math.ceil(thCdLeft())} giây`);
  let dest = thKeyName(k);
  if (k === "town") {
    if (R.town) return toast(`Đang ở ${W.town.n}`);
    if (!thToTown()) return;
  } else if (k.startsWith("v:")) {
    const [, id, pi] = k.split(":"),
      d = thDest(id);
    if (!d) return;
    if (!thAvail(d)) return toast(`Chưa có dữ liệu bản đồ ${d.n}`);
    const pt = (d.p && d.p[+pi || 0]) || [d.n, d.x, d.y],
      p = thPlan(d);
    if (p.lock && !(p.migu && miguBypass())) return toast(`Cần cấp ${p.need}`);
    // Mật Cốc: pay the pass now that the map is loaded (or ask / wait for the server: travel later)
    const madm = p.migu && miguBypass() && !miguActive();
    if (p.migu && !miguPay(k)) return;
    if (p.kind === "town") {
      const prev = { id: W.town.id, n: W.town.n, bg: W.town.bg },
        prevT = S.thTown;
      thSetTown(d);
      jxmLand(d.id, pt[1], pt[2]);
      JXM.landPending = String(d.id);
      if (!thToTown()) return (Object.assign(W.town, prev), prevT == null ? delete S.thTown : (S.thTown = prevT));
      R.banner = { t: 2.2, text: d.n, sub: `${TH_NAME} · ${d.t === "Battlefield" ? "khu an toàn" : "thành thị"}` };
      $("#townName") && ($("#townName").textContent = d.n);
    } else {
      let a = p.a;
      if (p.kind === "visit") a = thVisitAlt(p.z, d);
      p.migu && miguAlt(ZALT[p.z][a - 1], d, +pi || 0);
      const old = JXM.lands[String(d.id)];
      jxmLand(d.id, pt[1], pt[2]);
      const pend = JXM.landPending;
      JXM.landPending = String(d.id);
      const here = !R.town && thCur() === p.z && ((S.zalt || {})[p.z] || 0) === a;
      if (here && JXM.cur && String(JXM.cur.id) === String(d.id)) {
        // another landing point of the map we are on (Mật Cốc: another valley): re-land, camps laid out again
        if (old && old[0] === pt[1] && old[1] === pt[2])
          return (toast(`Đang ở ${d.n}`), void (JXM.landPending = pend));
        // loot on the ground comes along (same place relative to the hero) instead of being snapped onto the
        // valley edge nearest to the old spot, where auto-loot would walk the hero into the cliff
        const gx = pt[1] - H.x,
          gy = pt[2] - H.y;
        for (const o of R.ground || []) ((o.x += gx), (o.y += gy));
        obsLoad(OBS.key); // walkable area of the new landing point (jxmLandComp), puts the hero there
        ((R.enemies = R.enemies.filter((e) => (e.goldBoss || e.sat || e.satG) && !e.dead)), (R.corpses = []));
        ((R.field = null), (R.pickTarget = null), (R.moveTo = null), (INPUT.target = null));
        R.banner = { t: 2.2, text: d.n, sub: `${TH_NAME} · ${pt[0]}` };
      } else if (!thToZone(p.z, a, `${TH_NAME} · ${d.lv ? `cấp ${d.lv}` : `Cấp ${ZONES[p.z].lo}–${ZONES[p.z].hi}`}`))
        return void (JXM.landPending = pend);
      p.kind === "visit" ? (S.thv = { id: d.id, z: p.z, a, x: pt[1], y: pt[2] }) : delete S.thv;
      p.migu && S.thv && ((S.thv.pi = +pi || 0), madm ? (S.thv.adm = 1) : delete S.thv.adm);
    }
  } else {
    const [z, a] = k.split(":").map(Number);
    if (!ZONES[z]) return;
    if (!zoneOpen(z)) return toast(`Cần cấp ${thLv(ZONES[z])}`);
    JXM.landPending = null;
    if (!thToZone(z, a)) return;
  }
  R.thAt = Date.now() + TH_CD * 1e3;
  uiSfx("use");
  log(`Dùng ${TH_NAME} tới <b>${esc(dest)}</b>.`);
  closeModal(!0);
  save();
  refresh();
}
// After a save is loaded: last town (Thổ Địa Phù target) and an active field visit map.
function thRestore() {
  if (!S || typeof W != "object" || !W.town) return;
  Object.assign(W.town, TH_TOWN0);
  const t = S.thTown != null && thDest(S.thTown);
  t && t.safe ? thSetTown(t) : delete S.thTown;
  const v = S.thv,
    d = v && thDest(v.id);
  if (d && ZONES[v.z] && !d.safe && !thZoneKey(d.id)) {
    const a = thVisitAlt(v.z, d);
    typeof miguIs == "function" && miguIs(d) && miguAlt(ZALT[v.z][a - 1], d, v.pi);
    S.zalt && S.zalt[v.z] === v.a && (S.zalt[v.z] = a);
    v.a = a;
    typeof jxmLand == "function" && (jxmLand(d.id, v.x, v.y), (JXM.landPending = String(d.id)));
  } else delete S.thv;
}
// Town landing points (JX1 revive points) for every safe destination: Thổ Địa Phù lands there too.
function thLands() {
  if (typeof jxmLand != "function") return;
  for (const d of thDests()) d.safe && !JXM.lands[String(d.id)] && jxmLand(d.id, d.x, d.y);
}
// Hook the save loader now (main.js init() calls load() before DOMContentLoaded).
if (typeof load == "function") {
  const o = load;
  load = function () {
    const r = o.apply(this, arguments);
    try {
      thLands();
      thRestore();
    } catch (e) {
      console.warn("thRestore", e);
    }
    return r;
  };
}
// Back from town onto a visit map: land on its landing point again (camps are around it).
if (typeof backFromTown == "function") {
  const o = backFromTown;
  backFromTown = function () {
    typeof miguBackOk == "function" && miguBackOk();
    try {
      const z = zoneOf(Math.min(S.stage, STAGES));
      R.town && z && z.thv && typeof JXM == "object" && (JXM.landPending = String(z.id));
    } catch {}
    return o.apply(this, arguments);
  };
}

// ---- Shop rows (Cửa hàng + Kỳ Trân Các) ----
function thBuy() {
  if (S.gold < TH_GOLD) return toast("Không đủ ngân lượng");
  S.gold -= TH_GOLD;
  matAdd("misc", TH_KEY, 1);
  log(`Mua <b>${TH_NAME}</b> (−${fmtL(TH_GOLD)} lượng).`);
  toast(`Nhận 1 ${TH_NAME} (phím 4)`);
  uiSfx("use");
  invDirty = !0;
  save();
}
function thShopRow() {
  if (typeof shopTab == "undefined" || shopTab !== "med") return; // Dược phẩm (tạp hóa) tab
  const l = $("#mBody .shoplist");
  if (!l || l.querySelector("[data-thbuy]")) return;
  const h = thHave();
  l.insertAdjacentHTML(
    "afterbegin",
    `<button class="shoprow" data-thbuy="1"><img src="${TH_IC}" alt=""><span><b>${TH_NAME}</b><small>Dịch chuyển tới thành thị / bãi luyện công · dùng mãi, hồi ${TH_CD} giây${h ? ` · đang có ${h}` : ""}</small></span><em>${fmt(TH_GOLD)}</em></button>`,
  );
  l.querySelector("[data-thbuy]").onclick = () => {
    (thBuy(), shopModal());
  };
}
// ---- Inventory strip ("Hành trang") ----
function thInvRow() {
  const t = $("#t-inv");
  if (!t || !S || !S.fac || t.querySelector(".thinv")) return;
  const h = thHave(),
    html = `<div class="thinv"><button class="it" data-thuse="1" title="${TH_NAME}: dịch chuyển (phím 4)"><img src="${TH_IC}" alt=""><i>${h}</i></button><span><b>${TH_NAME}</b><small>${h ? "Bấm để chọn nơi dịch chuyển" : "Mua ở Cửa hàng / Kỳ Trân Các"}</small></span><button class="btn sm${h ? " on" : ""}" data-thuse="1">Dùng</button></div>`,
    m = t.querySelector(".u2bag .u2money"),
    g = t.querySelector(".invgrid");
  if (m) m.insertAdjacentHTML("beforebegin", html);
  else if (g) g.insertAdjacentHTML("afterend", html);
  else return;
  t.querySelectorAll("[data-thuse]").forEach((e) => (e.onclick = thUse));
}
function thGrant() {
  if (!S || !S.fac || S.thpG) return;
  S.thpG = 1;
  thHave() < 1 && matAdd("misc", TH_KEY, 1);
  log(`🎁 Nhận <b>${TH_NAME}</b>: dịch chuyển tới thành thị / bãi luyện công (phím 4 hoặc Hành trang).`);
  typeof save == "function" && save();
}

const TH_CSS = `
img[src$="ldp.png?th"],#pad .pbtn.th i{filter:hue-rotate(185deg) saturate(1.2)}
#pad .pbtn.th i{background-image:url(img/ep/ldp.png)}
.pbtn.th{background:radial-gradient(#3a9ac9,#08263a)}
.thlist{max-height:56vh}
.thq{width:100%;box-sizing:border-box;margin:0 0 6px;padding:5px 8px;border:1px solid var(--line,#3e3c30);border-radius:5px;background:var(--panel2,#1d1b14);color:inherit;font:inherit}
.thgrp{display:grid;gap:3px}
.thpts{display:flex;flex-wrap:wrap;gap:4px;margin:0 0 2px 14px}
.thpts .btn{padding:1px 8px;font-size:11px}
.thlist [hidden]{display:none!important}
.thlist .thh{color:var(--gold,#e0c060);font-weight:bold;margin:6px 0 2px;font-size:13px}
.thlist .thrw.nt{grid-template-columns:1fr auto}
.thlist .thrw img{width:48px;height:36px;object-fit:cover;image-rendering:auto}
.thlist .thrw.alt{margin-left:14px}
.thlist .thrw[disabled]{cursor:not-allowed}
.thic{height:18px;vertical-align:middle;image-rendering:pixelated}
.thinv{display:flex;align-items:center;gap:8px;margin:6px 0;padding:4px 6px;border:1px solid var(--line,#3e3c30);border-radius:5px}
.thinv>span{flex:1;min-width:0}
.thinv small{display:block;color:var(--dim,#bdb59a);font-size:11px}
.thinv .it{position:relative;width:36px;height:36px;flex:none}
.thinv .it img{width:100%;height:100%;object-fit:contain;image-rendering:pixelated}
`;

function thInstall() {
  const st = document.createElement("style");
  st.textContent = TH_CSS;
  document.head.appendChild(st);
  typeof MISC_N == "object" && (MISC_N[TH_KEY] = TH_NAME);
  // Kỳ Trân Các (both the classic list and the u20 category view).
  typeof KTC != "undefined" &&
    !KTC.some((e) => e.k === TH_KEY) &&
    KTC.push({
      k: TH_KEY,
      n: TH_NAME,
      ic: TH_IC,
      gold: TH_GOLD,
      d: `Dịch chuyển tới thành thị / bãi luyện công đã mở · dùng mãi, hồi ${TH_CD} giây (phím 4 hoặc Hành trang)`,
      use: () => (matAdd("misc", TH_KEY, 1), `Nhận 1 ${TH_NAME}`),
    });
  typeof KTC_CAT != "undefined" && KTC_CAT[0] && !KTC_CAT[0][1].includes(TH_KEY) && KTC_CAT[0][1].push(TH_KEY);
  // Hook existing UI functions (wrapped by global name so later reassignments still flow through).
  if (typeof shopModal == "function") {
    const o = shopModal;
    shopModal = function () {
      const r = o.apply(this, arguments);
      try {
        thShopRow();
      } catch {}
      return r;
    };
  }
  if (typeof renderInv == "function") {
    const o = renderInv;
    renderInv = function () {
      const r = o.apply(this, arguments);
      try {
        thInvRow();
      } catch {}
      return r;
    };
  }
  if (typeof updatePadCd == "function") {
    const o = updatePadCd;
    updatePadCd = function () {
      const r = o.apply(this, arguments),
        b = $("#bTh");
      b && b.querySelector(".cd").style.setProperty("--p", `${clamp(thCdLeft() / TH_CD, 0, 1) * 100}%`);
      return r;
    };
  }
  if (typeof createCharacter == "function") {
    const o = createCharacter;
    createCharacter = function () {
      const r = o.apply(this, arguments);
      try {
        thGrant();
      } catch {}
      return r;
    };
  }
  // Hotbar button (#bTh, next to Thổ Địa Phù) + key 4.
  const btn = $("#bTh");
  btn &&
    btn.addEventListener("pointerdown", (e) => {
      (e.preventDefault(), e.stopPropagation(), e.button !== 2 && thUse());
    });
  window.addEventListener("keydown", (e) => {
    if (e.repeat || e.key !== "4" || /INPUT|TEXTAREA|SELECT/.test(e.target.tagName)) return;
    const mb = $("#modal");
    if (mb && !mb.classList.contains("hidden") && $("#mBody .thlist")) return closeModal();
    thUse();
  });
  thGrant();
  thLands();
  setInterval(() => {
    try {
      thGrant();
    } catch {}
  }, 3e3);
}
document.readyState === "loading" ? document.addEventListener("DOMContentLoaded", thInstall) : setTimeout(thInstall, 0);
